import '../styles/globals.css'
import React from 'react';
import type {AppProps} from 'next/app'
import Head from "next/head";
import Layout from "../src/common/components/Layout";
import {RootState, store} from "../store"
import {Provider, useSelector} from "react-redux";
import ScheduleModal from "../src/calendar/components/ScheduleModal"


function App({Component, pageProps}: AppProps) {
    return (
        <Provider store={store}>
            <React.Fragment>
                <Head>
                    <title>Google Calendar</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Layout>
                    <Component {...pageProps} />
                </Layout>
            </React.Fragment>
        </Provider>
    )
}

export default App
